name: 'Trigger AWX job templates through REST APIs'
description: 'Github action that allows you to trigger job templates via API call on AWX'
author: 'bilalahmad99'
inputs:
  ansible_tower_user:
    description: 'Ansible Tower or AWX User'
    required: true
  ansible_tower_pass:
    description: 'Ansible Tower or AWX Password'
    required: true
  ansible_tower_url:
    description: 'Ansible Tower or AWX URL'
    required: true
  job_template_id:
    description: 'Job Template ID on Ansible Tower or AWX'
    required: true
  extra_vars:
    description: 'Extra vars required by the job template'
    required: true
outputs:
  RESOURCE_NAME:
    description: 'Component resource name output'
runs:
  using: 'node16'
  main: 'dist/index.js'
